// Generado a partir de la carpeta de fotos que entrego el cliente.
// Cada evento es un trabajo real; sus fotos viven en public/galeria/<slug>/01.jpg..NN.jpg
export const eventos = [
  { slug: "boda-finca", cat: "Boda", titulo: "Boda — Finca en Osona", n: 32 },
  { slug: "boda-jardin", cat: "Boda", titulo: "Boda — Ceremonia en el jardín", n: 5 },
  { slug: "preboda-pueblo", cat: "Preboda", titulo: "Preboda — Pueblo medieval", n: 8 },
  { slug: "preboda-campo", cat: "Preboda", titulo: "Preboda — Entre montañas", n: 5 },
  { slug: "quince-celeste", cat: "Quinceañera", titulo: "Quinceañera — Vestido celeste", n: 8 },
  { slug: "quince-menta", cat: "Quinceañera", titulo: "Quinceañera — Vestido menta", n: 12 },
  { slug: "quince-esmeralda", cat: "Quinceañera", titulo: "Quinceañera — Sesión en verde", n: 4 },
  { slug: "prequince-urbano", cat: "Pre-quince", titulo: "Pre-quince — Sesión urbana", n: 12 },
  { slug: "prequince-bosque", cat: "Pre-quince", titulo: "Pre-quince — Bosque y ciudad", n: 13 },
  { slug: "comunion-vic", cat: "Comunión", titulo: "Comunión — Calles de Vic", n: 10 },
  { slug: "comunion-ceremonia", cat: "Comunión", titulo: "Comunión — La ceremonia", n: 9 },
  { slug: "comunion-iglesia", cat: "Comunión", titulo: "Comunión — En la iglesia", n: 7 },
  { slug: "comunion-retrato", cat: "Comunión", titulo: "Comunión — Retrato en exteriores", n: 8 },
];

// Las 16 piezas de la reticula. Cada una abre el carrusel de su evento.
export const portadas = [
  { img: "01.jpg", slug: "boda-finca", size: "wide", ratio: "900 / 600",
    alt: "Los novios saliendo entre los invitados tras la ceremonia de su boda en Osona" },
  { img: "02.jpg", slug: "quince-celeste", size: "narrow", ratio: "600 / 900",
    alt: "Quinceañera con vestido celeste y corona posando en un jardín" },
  { img: "03.jpg", slug: "preboda-pueblo", size: "", ratio: "600 / 900",
    alt: "Pareja al fondo de unas escaleras de piedra en un pueblo medieval, sesión de preboda" },
  { img: "04.jpg", slug: "comunion-vic", size: "", ratio: "675 / 900",
    alt: "Niña de primera comunión apoyada en un muro de piedra en Vic" },
  { img: "05.jpg", slug: "prequince-bosque", size: "narrow", ratio: "600 / 900",
    alt: "Retrato de pre-quince apoyada en el tronco de un pino" },
  { img: "06.jpg", slug: "boda-finca", size: "narrow", ratio: "600 / 900",
    alt: "Los novios besándose durante el cóctel de su boda en una finca de Osona" },
  { img: "07.jpg", slug: "quince-menta", size: "narrow", ratio: "600 / 900",
    alt: "Retrato de quinceañera con vestido menta y corona" },
  { img: "08.jpg", slug: "comunion-iglesia", size: "", ratio: "600 / 900",
    alt: "Niño de primera comunión en el pasillo central ante el altar dorado" },
  { img: "09.jpg", slug: "prequince-urbano", size: "", ratio: "600 / 900",
    alt: "Sesión de pre-quince con camisa azul en un parque de Vic" },
  { img: "10.jpg", slug: "boda-jardin", size: "narrow", ratio: "577 / 900",
    alt: "Novios abrazados con el ramo de flores azules en el jardín" },
  { img: "11.jpg", slug: "preboda-campo", size: "wide", ratio: "900 / 600",
    alt: "Pareja riendo con las montañas de Osona al fondo durante su sesión de preboda" },
  { img: "12.jpg", slug: "comunion-ceremonia", size: "", ratio: "600 / 900",
    alt: "Niña de comunión rezando con corona y velo de encaje" },
  { img: "13.jpg", slug: "quince-esmeralda", size: "", ratio: "600 / 900",
    alt: "Quinceañera con vestido verde esmeralda apoyada en una barandilla" },
  { img: "14.jpg", slug: "comunion-retrato", size: "narrow", ratio: "589 / 900",
    alt: "Niño de primera comunión caminando por una avenida arbolada de Vic" },
  { img: "15.jpg", slug: "quince-menta", size: "narrow", ratio: "600 / 900",
    alt: "Quinceañera con vestido menta ante una decoración de globos dorados" },
  { img: "16.jpg", slug: "prequince-bosque", size: "narrow", ratio: "600 / 900",
    alt: "Retrato de pre-quince entre las hojas con luz de atardecer" },
];
